name: Reservation

on:
  # 定时触发
  workflow_dispatch:
  # schedule:
  # - cron: '53 * * * *'  # 每天7点执行
  # push:
  # pull_request:

jobs:
  run-first-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 指定Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 如果有依赖，确保您在仓库中添加了requirements.txt文件

    - name: set beijing timezone
      uses: szenius/set-timezone@v1.2 # 设置虚拟环境的时区，可更改时区
      with:
        timezoneLinux: "Asia/Shanghai"

    - name: Run the script
      run: python task.py --username ${{secrets.USERNAME}} --password ${{secrets.PASSWORD}} --reservation-arena 江湾体育馆羽毛球场  --reservation-time 15:00,16:00,17:00 --capcha-username ${{secrets.CAPCHA_USERNAME}} --capcha-password ${{secrets.CAPCHA_PASSWORD}} --receive-email ${{secrets.RECEIVE_EMAIL}} --send-email ${{secrets.SEND_EMAIL}} --send-email-key ${{secrets.SEND_EMAIL_KEY}}

  
