name: Schedule Script

on:
  schedule:
    - cron: '54 8 * * *'  # 每天7点执行
  # push:
  # pull_request:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2



    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 指定Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 如果有依赖，确保您在仓库中添加了requirements.txt文件

    - name: Run the script
      run: python task.py --username ${{secrets.USERNAME}} --password ${{secrets.PASSWORD}} --reservation-arena 江湾体育馆羽毛球场  --reservation-time 15:00

    - name: Run the script for the second arena
      run: python task.py --username ${{secrets.USERNAME}} --password ${{secrets.PASSWORD}} --reservation-arena 江湾体育馆羽毛球场  --reservation-time 16:00